apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: auth-redis
  labels:
    app: auth-redis
spec:
  selector:
    matchLabels:
      app: auth-redis
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-redis
        tier: backend
    spec:
      containers:
      - name: auth-redis
        image: redis:latest
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis
  labels:
    app: auth-redis
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: auth-redis
    tier: backend
