apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      tier: service
  template:
    metadata:
      labels:
        app: auth-service
        tier: service
    spec:
      containers:
      - name: service-proxy
        image: hypertube/service-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
      - name: proxy-ext-authz
        image: hypertube/service-proxy-authz
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10003
      - name: auth-service
        image: hypertube/auth-service
        imagePullPolicy: IfNotPresent
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    tier: service
spec:
  type: NodePort
  ports:
  # here we expose only your service proxy port
  - port: 8000
  selector:
    app: auth-service
    tier: service
